#!/usr/bin/env bash
#
# Git commit-msg hook to prevent commits with AI attribution labels.
# Called by husky via .husky/commit-msg.

set -eo pipefail

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

simple_patterns=(
  "generated with"
  "generated by"
  "co-authored-by: claude"
  "co-authored-by: chatgpt"
  "co-authored-by: bard"
  "co-authored-by: copilot"
  "🤖"
)

regex_patterns=(
  "generated\s+(by|with)[:]\s*\[?[a-zA-Z0-9\s\-_]+\]?"
  "co-authored-by:\s*(claude|chatgpt|gpt|bard|copilot|ai|llm|gemini)\s*(<.*>)?"
  "((created|written|produced)\s+(by|with|using)\s+(claude|chatgpt|gpt|bard|copilot|gemini|ai|llm))"
)

found_banned_pattern=false
matched_pattern=""

for pattern in "${simple_patterns[@]}"; do
  if echo "$COMMIT_MSG" | grep -iqF "$pattern"; then
    matched_pattern="$pattern"
    found_banned_pattern=true
    break
  fi
done

if [ "$found_banned_pattern" = false ]; then
  for pattern in "${regex_patterns[@]}"; do
    if echo "$COMMIT_MSG" | grep -iqE "$pattern"; then
      matched_pattern="$pattern (regex)"
      found_banned_pattern=true
      break
    fi
  done
fi

if [ "$found_banned_pattern" = true ]; then
  echo "" >&2
  echo "================================================================" >&2
  echo "COMMIT REJECTED: AI attribution detected in commit message" >&2
  echo "================================================================" >&2
  echo "" >&2
  echo "Found banned pattern: '$matched_pattern'" >&2
  echo "" >&2
  echo "Remove any of the following from your commit message:" >&2
  echo "  - 'Generated with/by [AI tool]' labels" >&2
  echo "  - 'Co-authored-by: Claude/ChatGPT/etc.' attributions" >&2
  echo "  - Robot emojis or similar AI indicators" >&2
  echo "" >&2
  exit 1
fi

exit 0
